<a href="https://colab.research.google.com/github/neha-bhansali/Automated-License-Plate-Detection/blob/main/Problem%203/etl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
!wget -O 'nested_data.json' 'https://file.notion.so/f/s/98b0fa4b-2a85-40e0-af20-5a2785c55c92/Untitled.json?id=b6059ad3-5ee5-4f32-84b6-b03e68bdca98&table=block&spaceId=ca71608c-1cc3-4167-857a-24da97c78717&expirationTimestamp=1692885600000&signature=9bnPSJzT_B1ProiZczFxEz5XpGvOZqY8kEW9Bm9DW4Q&downloadName=nested_data.json'

--2023-08-23 13:26:25--  https://file.notion.so/f/s/98b0fa4b-2a85-40e0-af20-5a2785c55c92/Untitled.json?id=b6059ad3-5ee5-4f32-84b6-b03e68bdca98&table=block&spaceId=ca71608c-1cc3-4167-857a-24da97c78717&expirationTimestamp=1692885600000&signature=9bnPSJzT_B1ProiZczFxEz5XpGvOZqY8kEW9Bm9DW4Q&downloadName=nested_data.json
Resolving file.notion.so (file.notion.so)... 13.224.2.120, 13.224.2.89, 13.224.2.128, ...
Connecting to file.notion.so (file.notion.so)|13.224.2.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22924462 (22M) [application/json]
Saving to: ‘nested_data.json’

nested_data.json    100%[===================>]  21.86M  58.3MB/s    in 0.4s

2023-08-23 13:26:26 (58.3 MB/s) - ‘nested_data.json’ saved [22924462/22924462]

In [3]:
data = pd.read_json('nested_data.json')

In [4]:
data.head()

                                            programs
0  {'season': '1842-43', 'orchestra': 'New York P...
1  {'season': '1842-43', 'orchestra': 'New York P...
2  {'season': '1842-43', 'orchestra': 'Musicians ...
3  {'season': '1842-43', 'orchestra': 'New York P...
4  {'season': '1843-44', 'orchestra': 'New York P...

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13954 entries, 0 to 13953
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   programs  13954 non-null  object
dtypes: object(1)
memory usage: 109.1+ KB

In [6]:
data['programs'][3]

{'season': '1842-43',
 'orchestra': 'New York Philharmonic',
 'concerts': [{'Date': '1843-04-22T05:00:00Z',
   'eventType': 'Subscription Season',
   'Venue': 'Apollo Rooms',
   'Location': 'Manhattan, NY',
   'Time': '8:00PM'}],
 'programID': '5887',
 'works': [{'workTitle': 'SYMPHONY NO. 2 IN D MAJOR, OP.36',
   'conductorName': 'Boucher, Alfred',
   'ID': '52434*',
   'soloists': [],
   'composerName': 'Beethoven,  Ludwig  van'},
  {'workTitle': 'SYMPATHY, HXXVIA:33 (VOICE AND ORCH) (ARR. Loder)',
   'conductorName': 'Loder, George',
   'ID': '3666*',
   'soloists': [{'soloistName': 'Loder, Edward',
     'soloistRoles': 'S',
     'soloistInstrument': 'Vocalist'}],
   'composerName': 'Haydn,  Franz  Joseph'},
  {'workTitle': "MIDSUMMER NIGHT'S DREAM, OP. 61",
   'composerName': 'Mendelssohn,  Felix',
   'conductorName': 'Loder, George',
   'ID': '5801*1',
   'soloists': [],
   'movement': 'Overture'},
  {'interval': 'Intermission', 'ID': '0*', 'soloists': []},
  {'workTitle': 'SEPTET, E-FLAT MAJOR, OP.20',
   'ID': '52425*',
   'soloists': [{'soloistName': 'Gröneveldt, W. Theodore',
     'soloistRoles': 'A',
     'soloistInstrument': 'Clarinet'},
    {'soloistName': 'Reiff, Anton, Sr.',
     'soloistRoles': 'A',
     'soloistInstrument': 'Bassoon'},
    {'soloistName': 'Trojsi, Gaetano',
     'soloistRoles': 'A',
     'soloistInstrument': 'French Horn'},
    {'soloistName': 'Hill, Ureli Corelli',
     'soloistRoles': 'A',
     'soloistInstrument': 'Violin'},
    {'soloistName': 'Wiegers, Louis',
     'soloistRoles': 'A',
     'soloistInstrument': 'Viola'},
    {'soloistName': 'Boucher, Alfred',
     'soloistRoles': 'A',
     'soloistInstrument': 'Cello'},
    {'soloistName': 'Rosier, F. W.',
     'soloistRoles': 'A',
     'soloistInstrument': 'Contrabass'}],
   'composerName': 'Beethoven,  Ludwig  van'},
  {'workTitle': "E MI LASCI COSÌ? ... TU M'ABBANDONI, INGRATO, OP. 71",
   'conductorName': 'Loder, George',
   'ID': '3674*',
   'soloists': [{'soloistName': 'Loder, Edward',
     'soloistRoles': 'S',
     'soloistInstrument': 'Vocalist'}],
   'composerName': 'Spohr,  Louis'},
  {'workTitle': 'JUBEL OVERTURE, OP. 59',
   'conductorName': 'Loder, George',
   'ID': '50729*',
   'soloists': [],
   'composerName': 'Weber,  Carl  Maria Von'}],
 'id': '34ec2c2b-3297-4716-9831-b538310462b7'}

In [7]:
programs = pd.json_normalize(data['programs'])

In [8]:
programs.head()

,season,orchestra,concerts,programID,works,id
0,1842-43,New York Philharmonic,"[{'Date': '1842-12-07T05:00:00Z', 'eventType':...",3853,"[{'workTitle': 'SYMPHONY NO. 5 IN C MINOR, OP....",38e072a7-8fc9-4f9a-8eac-3957905c0002
1,1842-43,New York Philharmonic,"[{'Date': '1843-02-18T05:00:00Z', 'eventType':...",5178,[{'workTitle': 'SYMPHONY NO. 3 IN E FLAT MAJOR...,c7b2b95c-5e0b-431c-a340-5b37fc860b34
2,1842-43,Musicians from the New York Philharmonic,"[{'Date': '1843-04-07T05:00:00Z', 'eventType':...",10785,"[{'workTitle': 'EGMONT, OP.84', 'composerName'...",894e1a52-1ae5-4fa7-aec0-b99997555a37
3,1842-43,New York Philharmonic,"[{'Date': '1843-04-22T05:00:00Z', 'eventType':...",5887,"[{'workTitle': 'SYMPHONY NO. 2 IN D MAJOR, OP....",34ec2c2b-3297-4716-9831-b538310462b7
4,1843-44,New York Philharmonic,"[{'Date': '1843-11-18T05:00:00Z', 'eventType':...",305,"[{'workTitle': 'SYMPHONY NO. 7 IN A MAJOR, OP....",610a4acc-94e4-4cd6-bdc1-8ad020edc7e9

In [9]:
d = pd.json_normalize(data['programs'], 'concerts')

In [10]:
d

,Date,eventType,Venue,Location,Time
0,1842-12-07T05:00:00Z,Subscription Season,Apollo Rooms,"Manhattan, NY",8:00PM
1,1843-02-18T05:00:00Z,Subscription Season,Apollo Rooms,"Manhattan, NY",8:00PM
2,1843-04-07T05:00:00Z,Special,Apollo Rooms,"Manhattan, NY",8:00PM
3,1843-04-22T05:00:00Z,Subscription Season,Apollo Rooms,"Manhattan, NY",8:00PM
4,1843-11-18T05:00:00Z,Subscription Season,Apollo Rooms,"Manhattan, NY",None
...,...,...,...,...,...
21602,2017-06-24T04:00:00Z,Chamber,Guild Hall,"East Hampton, NY",None
21603,2017-07-02T04:00:00Z,Tour,Shanghai Symphony Hall,"Shanghai, CHINA",7:30PM
21604,2017-07-03T04:00:00Z,Tour,Shanghai Symphony Hall,"Shanghai, CHINA",7:30PM
21605,2017-07-04T04:00:00Z,Tour - Young People's Concert,Shanghai Symphony Hall--Chamber Hall,"Shanghai, CHINA",7:30PM
21606,2017-07-07T04:00:00Z,Tour,Shanghai Symphony Hall,"Shanghai, CHINA",7:30PM

In [11]:
l = pd.json_normalize(data['programs'] , 'works')

In [12]:
l

,workTitle,conductorName,ID,soloists,composerName,movement,interval,movement.em,movement._,workTitle.em,workTitle._
0,"SYMPHONY NO. 5 IN C MINOR, OP.67","Hill, Ureli Corelli",52446*,[],"Beethoven, Ludwig van",NaN,NaN,NaN,NaN,NaN,NaN
1,OBERON,"Timm, Henry C.",8834*4,"[{'soloistName': 'Otto, Antoinette', 'soloistR...","Weber, Carl Maria Von","""Ozean, du Ungeheuer"" (Ocean, thou mighty mons...",NaN,NaN,NaN,NaN,NaN
2,"QUINTET, PIANO, D MINOR, OP. 74",NaN,3642*,"[{'soloistName': 'Scharfenberg, William', 'sol...","Hummel, Johann",NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,0*,[],NaN,NaN,Intermission,NaN,NaN,NaN,NaN
4,OBERON,"Etienne, Denis G.",8834*3,[],"Weber, Carl Maria Von",Overture,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
82788,MEMORIES OF MARNYI STONE,"Gersen, Joshua",12636*,[],"Feng, Shuya",NaN,NaN,NaN,NaN,NaN,NaN
82789,"SYMPHONY NO. 9, E MINOR, OP.95 (FROM THE NEW W...","Gersen, Joshua",2877*4,[],"Dvorak, Antonín",Allegro con fuoco,NaN,NaN,NaN,NaN,NaN
82790,QUIET CITY,"Gilbert, Alan",52332*,"[{'soloistName': 'Martin, Christopher', 'soloi...","Copland, Aaron",NaN,NaN,NaN,NaN,NaN,NaN
82791,"JUNGLE, THE (SYMPHONY NO. 4)","Gilbert, Alan",12071*,[{'soloistName': 'Jazz at Lincoln Center Orche...,"Marsalis, Wynton",NaN,NaN,NaN,NaN,NaN,NaN
82792,C JAM BLUES,NaN,8152*,[{'soloistName': 'Jazz at Lincoln Center Orche...,"Ellington, Duke",NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
x = pd.json_normalize(data['programs'] , ['works' , 'soloists'] )

In [14]:
x

,soloistName,soloistRoles,soloistInstrument
0,"Otto, Antoinette",S,Soprano
1,"Scharfenberg, William",A,Piano
2,"Hill, Ureli Corelli",A,Violin
3,"Derwort, G. H.",A,Viola
4,"Boucher, Alfred",A,Cello
...,...,...,...
56189,"Xu, Weiqin",S,Baritone
56190,"Martin, Christopher",S,Trumpet
56191,"Shryock, Grace",S,English Horn
56192,Jazz at Lincoln Center Orchestra with Wynton M...,S,Jazz Ensemble
56193,Jazz at Lincoln Center Orchestra with Wynton M...,S,Jazz Ensemble